# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories

# Exclude paths containing intentional test secrets
paths-ignore:
  # Leaky Repo benchmark - public test corpus of intentional secret leaks
  # Source: https://github.com/Plazmaz/leaky-repo
  # Purpose: Yologuard secret detection validation
  - 'code/yologuard/benchmarks/leaky-repo/**'

  # Yologuard test fixtures - synthetic secrets for unit tests
  - 'code/yologuard/tests/fixtures/**'

  # Yologuard benchmark scripts - may contain example patterns/documentation
  - 'code/yologuard/benchmarks/**/*.py'

  # Test data and examples
  - '**/tests/data/**'
  - '**/examples/**/*.example'

# Note: Real secrets should NEVER be committed.
# These exclusions are ONLY for public benchmark data and test fixtures.
